"""
Extend a Postman collection with requests generated from endpoint-inventory.json.

Preserves existing folders/items; adds a dedicated folder for generated endpoints.
Skips duplicates already present (by method + path template).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_COLLECTION = _REPO_ROOT / "docs/contracts/hotmart/Hotmart API — OrganicEcom.postman_collection.json"


def _iter_requests(items: list[dict]) -> Any:
    for it in items:
        if "item" in it:
            yield from _iter_requests(it["item"])
        else:
            yield it


def _extract_existing_keys(collection: dict) -> set[tuple[str, str]]:
    keys: set[tuple[str, str]] = set()
    for req in _iter_requests(collection.get("item", [])):
        try:
            method = req["request"]["method"].upper()
            raw = req["request"]["url"]["raw"]
            # Strip base variable prefix
            m = re.match(r"^\{\{base_url\}\}(/.*)$", raw)
            if m:
                path = m.group(1)
            else:
                path = raw
            path = path.split("?")[0]
            keys.add((method, path))
        except Exception:
            continue
    return keys


def _split_path_and_query(path_template: str) -> tuple[str, list[tuple[str, str]]]:
    if "?" in path_template:
        p, q = path_template.split("?", 1)
        q_pairs = parse_qsl(q, keep_blank_values=True)
        return p, q_pairs
    return path_template, []


def _path_segments(path: str) -> list[str]:
    p = path.strip()
    if not p.startswith("/"):
        p = "/" + p
    return [seg for seg in p.strip("/").split("/") if seg]


def _group_name(path_template: str) -> str:
    segs = _path_segments(path_template.split("?", 1)[0])
    if len(segs) >= 2 and segs[1] == "api":
        return f"{segs[0].title()} API"
    return segs[0].title() if segs else "Misc"


def build_request_item(method: str, path_template: str, confidence: str) -> dict[str, Any]:
    path_only, query_pairs = _split_path_and_query(path_template)
    segs = _path_segments(path_only)
    raw = "{{base_url}}/" + "/".join(segs)
    if query_pairs:
        q = "&".join(f"{k}={v}" for k, v in query_pairs)
        raw = raw + "?" + q

    query_objs: list[dict[str, Any]] = []
    for k, v in query_pairs:
        query_objs.append({"key": k, "value": v, "description": ""})

    url_obj: dict[str, Any] = {
        "raw": raw,
        "host": ["{{base_url}}"],
        "path": segs,
    }
    if query_objs:
        url_obj["query"] = query_objs

    return {
        "name": f"{method} {path_only}",
        "request": {
            "method": method,
            "header": [],
            "url": url_obj,
            "description": (
                "Auto-generated from Hotmart Developers docs (Gatsby `sample-code` extraction).\n\n"
                f"Confidence: {confidence}.\n"
                "Verify path/query placeholders against the official docs and your environment `base_url`."
            ),
        },
        "response": [],
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", type=Path, default=Path("output/endpoint-inventory.json"))
    ap.add_argument("--collection", type=Path, default=_DEFAULT_COLLECTION)
    ap.add_argument("--out", type=Path, default=None, help="Defaults to overwriting --collection")
    args = ap.parse_args()

    inv_path = args.inventory
    if not inv_path.exists():
        print(f"Missing {inv_path}", file=sys.stderr)
        return 2

    col_path = args.collection
    if not col_path.exists():
        print(f"Missing collection {col_path}", file=sys.stderr)
        return 2

    inventory = json.loads(inv_path.read_text(encoding="utf-8"))
    collection = json.loads(col_path.read_text(encoding="utf-8"))

    existing = _extract_existing_keys(collection)

    folder_name = "Generated — Hotmart docs (sample-code)"
    grouped: dict[str, list[dict]] = {}

    for ep in inventory.get("endpoints", []):
        method = str(ep.get("method", "")).upper()
        path_t = str(ep.get("path_template", ""))
        conf = str(ep.get("confidence", "medium"))
        if not method or not path_t.startswith("/"):
            continue

        path_only = path_t.split("?", 1)[0]
        key = (method, path_only)
        if key in existing:
            continue

        g = _group_name(path_t)
        grouped.setdefault(g, []).append(build_request_item(method, path_t, conf))

    new_folder = {
        "name": folder_name,
        "description": (
            "Requests generated by `scripts/hotmart-docs-crawl/postman_extend.py` from Hotmart docs "
            "static-query `sample-code` blocks. Review before relying on paths/params."
        ),
        "item": [],
    }

    for gname in sorted(grouped.keys()):
        new_folder["item"].append({"name": gname, "item": grouped[gname]})

    # Replace folder if already present
    items = collection.get("item", [])
    out_items: list[dict] = []
    replaced = False
    for it in items:
        if it.get("name") == folder_name:
            out_items.append(new_folder)
            replaced = True
        else:
            out_items.append(it)
    if not replaced:
        out_items.append(new_folder)

    collection["item"] = out_items

    out_path = args.out or col_path
    out_path.write_text(json.dumps(collection, indent=2), encoding="utf-8")
    print(f"Updated collection ({len(existing)} existing keys); wrote {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
